ProjektBDwAI/Models/HomeViewModel.cs
namespace ProjektBDwAI.Models
{
    public class HomeViewModel
    {
        public List<Survey> UserSurveys { get; set; }
        public List<Survey> PublicSurveys { get; set; }
    }
}

ProjektBDwAI/Models/UserpageViewModel.cs
namespace ProjektBDwAI.Models
{
    public class UserpageViewModel
    {
        public List<Survey> UserSurveys { get; set; }
    }
}

ProjektBDwAI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using ProjektBDwAI.Models;
using System.Diagnostics;

namespace ProjektBDwAI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ApplicationDbContext _context;

        public HomeController(ApplicationDbContext context)
        {
            _context = context;
        }

        private bool checkSession()
        {
            return HttpContext.Session.GetInt32("UserId").HasValue;
        }

        private int getSessionId()
        {
            if (checkSession())
            {
                return HttpContext.Session.GetInt32("UserId").Value;
            }

            return -1;

        }

        private int getSurveyOwnerId(int id)
        {
            return _context.Surveys.FirstOrDefault(s => s.Id == id).OwnerId;
        }

        private bool isAdmin()
        {
            if (HttpContext.Session.GetInt32("isAdmin") == 1)
            {
                return true;
            }
            else
            {
                return false;
            }
        }

        private bool isOwner(int id)
        {
            if (isAdmin())
            {
                return true;
            }
            return getSessionId() == getSurveyOwnerId(id);
        }

        public IActionResult Index()
        {
            if (HttpContext.Session.GetInt32("UserId").HasValue)
            {
                ViewData["Username"] = HttpContext.Session.GetString("Username");
                ViewData["UserId"] = HttpContext.Session.GetInt32("UserId");
                var userSurveys = _context.Surveys.Where(s => s.OwnerId == HttpContext.Session.GetInt32("UserId")).ToList();
                var publicSurveys = _context.Surveys.Where(s => s.IsPublic).ToList();

                var viewModel = new HomeViewModel
                {
                    UserSurveys = userSurveys,
                    PublicSurveys = publicSurveys
                };
                return View(viewModel);
            }

            return RedirectToAction("Login", "Account");
        }

        public IActionResult Privacy()
        {
            if (HttpContext.Session.GetInt32("UserId").HasValue)
            {
                return View();
            }
            return RedirectToAction("Login", "Account");
        }

        public IActionResult Userpage()
        {
            if (HttpContext.Session.GetInt32("UserId").HasValue)
            {
                int userId = HttpContext.Session.GetInt32("UserId").Value;
                ViewData["UserId"] = userId;
                ViewData["isAdmin"] = isAdmin();
                List<Survey> surveys = _context.Surveys.Where(s => s.OwnerId == userId).ToList();
                ViewData["UserSurveys"] = surveys;
                ViewData["AllSurveys"] = _context.Surveys.ToList();
                return View();
            }
            return RedirectToAction("Login", "Account");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

    }
}

ProjektBDwAI/Controllers/SurveyController.cs
using Azure;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjektBDwAI.Models;
using System.Security.Policy;

namespace ProjektBDwAI.Controllers
{
    public class SurveyController : Controller
    {
        private readonly ApplicationDbContext _context;

        private Survey getSurvey(int id)
        {
            var Survey = _context.Surveys.FirstOrDefault(s => s.Id == id);
            if (Survey != null)
            {
                return Survey;
            }
            return null;
            
        }

        private int getSurveyOwnerId(int id)
        {
            return _context.Surveys.FirstOrDefault(s => s.Id == id).OwnerId;
        }

        private bool isAdmin()
        {
            if (HttpContext.Session.GetInt32("isAdmin") == 1)
            {
                return true;
            } else
            {
                return false;
            }
        }

        private bool isOwner(int id)
        {
            if (isAdmin())
            {
                return true;
            }
            return getSessionId() == getSurveyOwnerId(id);
        }

        private string getAnswerContentById(int id)
        {
            return _context.Answers.FirstOrDefault(a => a.Id == id).Content.ToString();
        }

        private List<Question> getQuestions(int surveyId)
        {
            var Questions = _context.Questions.Where(q => q.SurveyId == surveyId).ToList();
            return Questions;
        }

        private List<Answer> getAnswers(List<Question> Questions)
        {
            List<Answer> Answers = new List<Answer>();
            foreach(var question in Questions)
            {
                Answers.AddRange(_context.Answers.Where(a => a.QuestionId == question.Id).ToList());
            }

            return Answers;
        }

        private bool checkSession()
        {
            return HttpContext.Session.GetInt32("UserId").HasValue;
        }

        private int getSessionId()
        {
            if (checkSession())
            {
                return HttpContext.Session.GetInt32("UserId").Value;
            }

            return -1;
            
        }

        private string getSessionUsername()
        {
            if (checkSession())
            {
                return HttpContext.Session.GetString("Username");
            }

            return "";
        }

        public SurveyController(ApplicationDbContext appDb)
        {
            _context = appDb;
        }
        public IActionResult Show(int Id)
        {
            if (checkSession())
            {
                SurveyShowModel viewModel = new SurveyShowModel();
                viewModel.Survey = _context.Surveys.FirstOrDefault(s => s.Id == Id);
                viewModel.Questions = getQuestions(Id);
                viewModel.Answers = getAnswers(viewModel.Questions);
                ViewData["isOwner"] = isOwner(Id);
                
                return View(viewModel);
            }
            return RedirectToAction("Login", "Account");
        }

        public IActionResult Edit(int Id) 
        {
            if (checkSession() && isOwner(Id)) { 
                SurveyEditModel viewModel = new SurveyEditModel();
                viewModel.Survey = _context.Surveys.FirstOrDefault(s => s.Id == Id);
                viewModel.Questions = getQuestions(viewModel.Survey.Id);
                viewModel.Answers = getAnswers(viewModel.Questions);
                return View(viewModel);
            } else if (checkSession() && !isOwner(Id))
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login", "Account");
        }
        public IActionResult Publish(int id)
        {
            if (checkSession() && isOwner(id))
            {
                Survey survey = _context.Surveys.FirstOrDefault(s => s.Id == id);
                survey.IsPublic = (!survey.IsPublic);
                _context.SaveChanges();
                return RedirectToAction("Show", new { Id = id });
            } else if (checkSession() && !isOwner(id))
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login", "Account");

        }

        public IActionResult Delete(int id)
        {
            if (checkSession() && isOwner(id))
            {
                Survey survey = _context.Surveys.FirstOrDefault(s => s.Id == id);
                _context.Surveys.Remove(survey);
                _context.SaveChanges();
                return RedirectToAction("Index", "Home");
            } else if (checkSession() && !isOwner(id))
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login", "Account");
            
        }

        public IActionResult Result(int id)
        {
            if (checkSession() && isOwner(id))
            {
                List<UserResult> userResults = _context.UserResults
                .Include(ur => ur.Question)
                .Include(ur => ur.Result)
                .Where(ur => ur.Result.SurveyId == id)
                .ToList();

                ViewData["SurveyId"] = id;
                foreach (var result in userResults)
                {
                    if (result.SelectedAnswer != "0")
                    {
                        ViewData[result.SelectedAnswer] = getAnswerContentById(int.Parse(result.SelectedAnswer));
                    }
                }
                var viewModel = new UserResultView
                {
                    UserResult = userResults
                };

                return View(viewModel);
            } else if (checkSession() && !isOwner(id))
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login", "Account");
            
        }
        [HttpPost]
        public async Task<IActionResult> Edit(SurveyEditModel model)
        {
            if (checkSession() && isOwner(model.surveyId))
            {


                switch (model.Action)
                {
                    case 1:
                        var question = new Question();
                        question.QuestionType = model.questionType;
                        question.SurveyId = model.surveyId;
                        question.Content = model.questionContent;

                        await _context.Questions.AddAsync(question);
                        await _context.SaveChangesAsync();
                        break;
                    case 2:
                        var answer = new Answer();
                        answer.QuestionId = model.questionId;
                        answer.Content = model.answerContent;
                        answer.Value = "A jak pan Marcin powiedzial?";
                        await _context.Answers.AddAsync(answer);
                        await _context.SaveChangesAsync();
                        break;
                    case 3:
                        var questionDel = _context.Questions.Find(model.questionId);
                        if (questionDel != null)
                        {
                            _context.Questions.Remove(questionDel);
                            _context.SaveChanges();
                        }
                        break;
                    case 4:
                        var answerDel = _context.Answers.Find(model.answerId);
                        if (answerDel != null)
                        {
                            _context.Answers.Remove(answerDel);
                            _context.SaveChanges();
                        }
                        break;
                    default:
                        break;
                }

                model.Survey = _context.Surveys.FirstOrDefault(s => s.Id == model.surveyId);
                model.Questions = getQuestions(model.Survey.Id);
                model.Answers = getAnswers(model.Questions);
                model.questionType = null;
                model.questionContent = null;
                return View(model);
            }

            return RedirectToAction("Login", "Account");
        }

        [HttpPost]
        public async Task<IActionResult> AddSurvey(Survey model)
        {
            if (checkSession()) {
                int userId = HttpContext.Session.GetInt32("UserId").Value;
                model.OwnerId = userId;
                model.IsPublic = false;
                _context.Surveys.Add(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Userpage", "Home");
                
            }
            return RedirectToAction("Userpage", "Home");
        }

        public IActionResult Fill(int Id)
        {
            if (checkSession() && isOwner(Id))
            {
                SurveyFillModel viewModel = new SurveyFillModel();
                ViewData["isOwner"] = isOwner(Id);
                viewModel.Survey = _context.Surveys.FirstOrDefault(s => s.Id == Id);
                if (viewModel.Survey == null)
                {
                    return RedirectToAction("Index", "Home");
                }
                viewModel.Questions = getQuestions(viewModel.Survey.Id);
                viewModel.Answers = getAnswers(viewModel.Questions);
                viewModel.Results = new List<string>();
                foreach (var question in viewModel.Questions)
                {
                    viewModel.Results.Add("");
                }
                ViewData["SurveyId"] = (int)viewModel.Survey.Id;

                return View(viewModel);
            } else if (checkSession() && !isOwner(Id))
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("Login", "Account");
        }
        [HttpPost]

ProjektBDwAI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @model HomeViewModel
}

<div class="text-center">
    <h1 class="display-4">Witaj @ViewData["Username"]</h1>
    <p>Czas zacząć tworzyć ankiety i przeprowadzać badania!</p>
    <div class="row">
        <div class="card col-6">
            <div class="card-header">
                <h2>Twoje ankiety</h2>
            </div>
            <div class="card-body">
                @foreach (var survey in Model.UserSurveys)
                {
                    <div class="row">
                        <a class="btn btn-primary col-12 p-2 m-1" asp-action="Show" asp-controller="Survey" asp-route-id="@survey.Id"> @survey.Title</a>
                    </div>
                }
            </div>
        </div>
        <div class="card col-6">
            <div class="card-header">
                <h2>Publiczne ankiety</h2>
            </div>
            <div class="card-body">
                @foreach(var survey in Model.PublicSurveys)
                {
                    <div class="row">
                        <a class="btn btn-primary col-12 p-2 m-1" asp-action="Show" asp-controller="Survey" asp-route-id="@survey.Id">@survey.Title</a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

ProjektBDwAI/Views/Home/Userpage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
@model Survey;
}

<div class="text-center">
    <div class="row">
        <div class="card col-8">
            <div class="card-header">
                <h1>Twoje ankiety</h1>
            </div>
            <div class="row justify-content-center">
                @foreach(var survey in ViewData["UserSurveys"] as List<Survey>)
                {
                    <a asp-action="Show" asp-controller="Survey" asp-route-id="@survey.Id" class="btn btn-primary col-10 offset-1 p-3 m-1">@survey.Title</a>
                }
            </div>
        </div>
        <div class="card col-4">
            <div class="card-header">
                <h1>Stwórz ankietę</h1>
            </div>
            <div class="card-body">
                <form asp-action="AddSurvey" asp-controller="Survey" method="post">
                    <div class="row">
                        <label asp-for="Title" class="form-label col-12">Tytuł</label>
                        <input asp-for="Title" class="form-text col-12" type="text" />
                        <span asp-validation-for="Title" class="text-danger col-4 offset-4"></span>
                        <input asp-for="OwnerId" hidden type="number" value="@ViewData["UserId"]" />
                    </div>
                    <div class="row">
                        <input type="submit" class="btn btn-primary col-4 offset-4 mt-4" value="Dodaj ankietę"/>
                    </div>
                </form>
            </div>
        </div>
        @if ((bool)ViewData["isAdmin"])
        {
            <div class="card col-8">
                <div class="card-header">
                    <h1>Wszystkie ankiety</h1>
                </div>
                <div class="card-body">
                    @foreach (var survey in ViewData["AllSurveys"] as List<Survey>)
                    {
                        <a asp-action="Show" asp-controller="Survey" asp-route-id="@survey.Id" class="btn btn-primary col-10 offset-1 p-3 m-1">@survey.Title</a>
                    }
                </div>
        </div>
        }
    </div>
</div>